"""
PDF Report Generator for CSE Stock Analyzer.
"""

from fpdf import FPDF
from datetime import datetime
import os
from src.utils.logger import get_logger

logger = get_logger(__name__)


class PDFReport(FPDF):
    """Custom PDF class with header and footer."""
    
    def header(self):
        # Logo could go here
        self.set_font('Helvetica', 'B', 15)
        self.cell(0, 10, 'CSE Stock Analyzer Report', 0, 1, 'C')
        self.ln(5)
        
    def footer(self):
        self.set_y(-15)
        self.set_font('Helvetica', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}/{{nb}} - Generated by CSE Stock Analyzer', 0, 0, 'C')


def generate_pdf_report(result, filepath):
    """
    Generate a comprehensive PDF report from analysis results.
    
    Args:
        result (dict): Complete analysis result dictionary
        filepath (str): Path to save the PDF file
    """
    logger.info(f"Generating PDF report for {result.get('stock_info', {}).get('ticker', 'Unknown')}")
    pdf = PDFReport()
    pdf.alias_nb_pages()
    pdf.add_page()
    
    # ── Title Section ─────────────────────────────────────────────
    
    stock_info = result.get('stock_info', {})
    ticker = stock_info.get('ticker', 'Unknown Ticker')
    company = stock_info.get('company_name', '')
    price = stock_info.get('current_price', 0)
    
    pdf.set_font('Helvetica', 'B', 12)
    pdf.cell(0, 10, f"Analysis for: {ticker} - {company}", 0, 1, 'L')
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, f"Current Price: LKR {price:,.2f}", 0, 1, 'L')
    pdf.cell(0, 6, f"Date: {datetime.now().strftime('%Y-%m-%d %H:%M')}", 0, 1, 'L')
    pdf.ln(5)
    
    # ── Executive Summary ─────────────────────────────────────────
    
    pdf.set_fill_color(30, 41, 59)  # Dark blue background
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, "  EXECUTIVE SUMMARY", 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)
    
    score = result.get('overall_score', 0)
    recommendation = result.get('recommendation', 'N/A')
    confidence = result.get('confidence', 'N/A')
    
    pdf.set_font('Helvetica', 'B', 14)
    
    # Color code the recommendation
    if score >= 80:
        pdf.set_text_color(22, 163, 74)  # Green
    elif score >= 55:
        pdf.set_text_color(234, 179, 8)  # Yellow/Orange
    else:
        pdf.set_text_color(220, 38, 38)  # Red
        
    pdf.cell(0, 10, f"{recommendation} (Score: {score}/100)", 0, 1, 'L')
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 10)
    pdf.cell(0, 6, f"Confidence Level: {confidence}", 0, 1, 'L')
    pdf.ln(5)
    
    # ── Key Insights ──────────────────────────────────────────────
    
    col_width = 90
    
    # Strengths
    pdf.set_font('Helvetica', 'B', 10)
    pdf.set_text_color(22, 163, 74)
    pdf.cell(col_width, 8, "Key Strengths", 0, 0, 'L')
    
    # Concerns
    pdf.set_text_color(220, 38, 38)
    pdf.cell(col_width, 8, "Key Concerns", 0, 1, 'L')
    
    # Reset text color
    pdf.set_text_color(0, 0, 0)
    pdf.set_font('Helvetica', '', 9)
    
    strengths = result.get('key_strengths', [])
    concerns = result.get('key_concerns', [])
    
    max_items = max(len(strengths), len(concerns))
    
    for i in range(max_items):
        # Strength item
        s_text = f"- {strengths[i]}" if i < len(strengths) else ""
        pdf.cell(col_width, 6, s_text, 0, 0, 'L')
        
        # Concern item
        c_text = f"- {concerns[i]}" if i < len(concerns) else ""
        pdf.cell(col_width, 6, c_text, 0, 1, 'L')
        
    pdf.ln(5)
    
    # ── Detailed Analysis ─────────────────────────────────────────
    
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, "  DETAILED ANALYSIS", 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)
    
    # Fundamental
    fund = result.get('fundamental_analysis', {})
    fund_score = fund.get('overall_score', 0) if fund else 0
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 8, f"Fundamental Analysis (Score: {fund_score})", 0, 1, 'L')
    pdf.set_font('Helvetica', '', 9)
    
    if fund and 'metrics' in fund:
        for metric, data in fund['metrics'].items():
            if isinstance(data, dict):
                val = data.get(metric, 'N/A')
                # Format value if float
                if isinstance(val, float):
                    val = f"{val:.2f}"
                interp = data.get('interpretation', '')
                pdf.cell(60, 6, f"{metric.replace('_', ' ').upper()}: {val}", 0, 0)
                pdf.cell(0, 6, f"({interp})", 0, 1)
    
    pdf.ln(3)
    
    # Technical
    tech = result.get('technical_analysis', {})
    tech_score = tech.get('overall_score', 0) if tech else 0
    signal = tech.get('overall_signal', 'N/A') if tech else 'N/A'
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 8, f"Technical Analysis (Score: {tech_score}) - {signal}", 0, 1, 'L')
    pdf.set_font('Helvetica', '', 9)
    
    if tech and 'indicators' in tech:
        indicators = tech['indicators']
        
        # RSI
        if 'rsi' in indicators and indicators['rsi'].get('rsi'):
            rsi = indicators['rsi']
            pdf.cell(60, 6, f"RSI (14): {rsi['rsi']}", 0, 0)
            pdf.cell(0, 6, f"({rsi['interpretation']})", 0, 1)
            
        # MACD
        if 'macd' in indicators and indicators['macd'].get('macd'):
            macd = indicators['macd']
            pdf.cell(60, 6, f"MACD: {macd['signal']}", 0, 0)
            pdf.cell(0, 6, f"({macd['interpretation']})", 0, 1)
            
        # Moving Averages
        if 'moving_averages' in indicators and indicators['moving_averages'].get('signal'):
            ma = indicators['moving_averages']
            pdf.cell(60, 6, f"Moving Averages: {ma['signal']}", 0, 0)
            pdf.cell(0, 6, f"({ma['interpretation']})", 0, 1)

    pdf.ln(3)
    
    # Risk
    risk = result.get('risk_assessment', {})
    risk_score = risk.get('risk_score', 0) if risk else 0
    level = risk.get('risk_level', 'N/A') if risk else 'N/A'
    
    pdf.set_font('Helvetica', 'B', 10)
    pdf.cell(0, 8, f"Risk Assessment (Score: {risk_score}) - {level}", 0, 1, 'L')
    pdf.set_font('Helvetica', '', 9)
    
    if risk and 'risk_factors' in risk:
        for factor in risk['risk_factors']:
            pdf.cell(0, 6, f"- {factor}", 0, 1)
            
    pdf.ln(5)
    
    # ── Action Items ──────────────────────────────────────────────
    
    pdf.set_fill_color(30, 41, 59)
    pdf.set_text_color(255, 255, 255)
    pdf.set_font('Helvetica', 'B', 11)
    pdf.cell(0, 8, "  ACTION ITEMS", 0, 1, 'L', fill=True)
    pdf.set_text_color(0, 0, 0)
    pdf.ln(2)
    
    actions = result.get('action_items', [])
    pdf.set_font('Helvetica', '', 10)
    if actions:
        for action in actions:
            pdf.cell(0, 6, f"[ ] {action}", 0, 1)
    else:
        pdf.cell(0, 6, "No specific actions recommended at this time.", 0, 1)
        
    # Disclaimer
    pdf.ln(10)
    pdf.set_font('Helvetica', 'I', 8)
    pdf.set_text_color(100, 100, 100)
    pdf.multi_cell(0, 4, "Disclaimer: This report is generated by an automated analysis tool. It does not constitute financial advice. Please verify all data and consult with a qualified financial advisor before making investment decisions.")
    
    pdf.output(filepath)
    logger.info(f"PDF report saved to {filepath}")
    return filepath
